name: label issue

on:
  issues:
    types: [opened, reopened]

jobs:
  label_issues:
    runs-on: ubuntu-latest

    permissions:
      issues: write

    steps:
      - name: Add label using gh CLI
        run: gh issue edit "$NUMBER" --add-label "$LABEL"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NUMBER: ${{ github.event.issue.number }}
          LABEL: triage
