name: Test Self-Hosted Runner

on:
  push:
    branches:
      - main

jobs:
  self-hosted-runner-job:
    runs-on: self-hosted

    steps:
      - name: Print message
        run: echo "Hello from self-hosted runner 🚀"

      - name: Check system info
        run: uname -a
